//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://release.niem.gov/niem/codes/iso_3166-1/3.0/")
package gov.niem.release.niem.codes.iso_3166_1._3;
