//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.structures._3.ObjectType;


/**
 * A data type for a representation of the identifying Biometric in.
 * 
 * <p>Java class for BiometricDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiometricDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}ObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}BiometricClassification" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}BiometricDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}BiometricImage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "BiometricDataType", propOrder = {
    "biometricClassification",
    "biometricDetail",
    "biometricImage"
})
public class BiometricDataType
    extends ObjectType
{

    @XmlElement(name = "BiometricClassification", nillable = true)
    protected BiometricClassificationType biometricClassification;
    @XmlElementRef(name = "BiometricDetail", namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> biometricDetail;
    @XmlElementRef(name = "BiometricImage", namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> biometricImage;

    /**
     * Gets the value of the biometricClassification property.
     * 
     * @return
     *     possible object is
     *     {@link BiometricClassificationType }
     *     
     */
    public BiometricClassificationType getBiometricClassification() {
        return biometricClassification;
    }

    /**
     * Sets the value of the biometricClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiometricClassificationType }
     *     
     */
    public void setBiometricClassification(BiometricClassificationType value) {
        this.biometricClassification = value;
    }

    /**
     * Gets the value of the biometricDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the biometricDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBiometricDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link MinutiaeType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getBiometricDetail() {
        if (biometricDetail == null) {
            biometricDetail = new ArrayList<JAXBElement<?>>();
        }
        return this.biometricDetail;
    }

    /**
     * Gets the value of the biometricImage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the biometricImage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBiometricImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IrisImageType }{@code >}
     * {@link JAXBElement }{@code <}{@link FaceImageType }{@code >}
     * {@link JAXBElement }{@code <}{@link FingerprintImageType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getBiometricImage() {
        if (biometricImage == null) {
            biometricImage = new ArrayList<JAXBElement<?>>();
        }
        return this.biometricImage;
    }

}
