//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FaceImageDescriptionCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FaceImageDescriptionCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ART EAR"/>
 *     &lt;enumeration value="ART EYE"/>
 *     &lt;enumeration value="ART L EAR"/>
 *     &lt;enumeration value="ART L EYE"/>
 *     &lt;enumeration value="ART R EAR"/>
 *     &lt;enumeration value="ART R EYE"/>
 *     &lt;enumeration value="BALD"/>
 *     &lt;enumeration value="BEARD"/>
 *     &lt;enumeration value="BLIND"/>
 *     &lt;enumeration value="BLINK"/>
 *     &lt;enumeration value="BLND EYE"/>
 *     &lt;enumeration value="BLND L EYE"/>
 *     &lt;enumeration value="BLND R EYE"/>
 *     &lt;enumeration value="BRAC TEETH"/>
 *     &lt;enumeration value="CATA L EYE"/>
 *     &lt;enumeration value="CATARACT"/>
 *     &lt;enumeration value="CATA R EYE"/>
 *     &lt;enumeration value="CAUL L EAR"/>
 *     &lt;enumeration value="CAUL R EAR"/>
 *     &lt;enumeration value="CLEAR GLASSES"/>
 *     &lt;enumeration value="CLEFT CHIN"/>
 *     &lt;enumeration value="CL LIP"/>
 *     &lt;enumeration value="CL LIP"/>
 *     &lt;enumeration value="CON LENSES"/>
 *     &lt;enumeration value="CROSSEYED"/>
 *     &lt;enumeration value="DARK GLASSES"/>
 *     &lt;enumeration value="DENT LOW"/>
 *     &lt;enumeration value="DENT UP"/>
 *     &lt;enumeration value="DENT UP LO"/>
 *     &lt;enumeration value="DIMP CHEEK"/>
 *     &lt;enumeration value="DIMP CHIN"/>
 *     &lt;enumeration value="DIMP FACE"/>
 *     &lt;enumeration value="DIMP L CHK"/>
 *     &lt;enumeration value="DIMP R CHK"/>
 *     &lt;enumeration value="DISC CHEEK"/>
 *     &lt;enumeration value="DISC CHIN"/>
 *     &lt;enumeration value="DISC EAR"/>
 *     &lt;enumeration value="DISC EYE"/>
 *     &lt;enumeration value="DISC FACE"/>
 *     &lt;enumeration value="DISC FHD"/>
 *     &lt;enumeration value="DISC HEAD"/>
 *     &lt;enumeration value="DISC L CHK"/>
 *     &lt;enumeration value="DISC L EAR"/>
 *     &lt;enumeration value="DISC L EYE"/>
 *     &lt;enumeration value="DISC LIP"/>
 *     &lt;enumeration value="DISC L LIP"/>
 *     &lt;enumeration value="DISC NOSE"/>
 *     &lt;enumeration value="DISC R CHK"/>
 *     &lt;enumeration value="DISC R EAR"/>
 *     &lt;enumeration value="DISC R EYE"/>
 *     &lt;enumeration value="DISC U LIP"/>
 *     &lt;enumeration value="DISTORTING CONDITION"/>
 *     &lt;enumeration value="EXTR L TTH"/>
 *     &lt;enumeration value="EXTR U TTH"/>
 *     &lt;enumeration value="EYES AWAY"/>
 *     &lt;enumeration value="FRC NOSE"/>
 *     &lt;enumeration value="FRC UL JAW"/>
 *     &lt;enumeration value="FRC UR JAW"/>
 *     &lt;enumeration value="FRECKLES"/>
 *     &lt;enumeration value="FROWNING"/>
 *     &lt;enumeration value="GLASSES"/>
 *     &lt;enumeration value="GOLD TOOTH"/>
 *     &lt;enumeration value="HAT"/>
 *     &lt;enumeration value="LEFT EYE PATCH"/>
 *     &lt;enumeration value="MC ACNE"/>
 *     &lt;enumeration value="MISS EAR"/>
 *     &lt;enumeration value="MISS EYE"/>
 *     &lt;enumeration value="MISS L EAR"/>
 *     &lt;enumeration value="MISS L EYE"/>
 *     &lt;enumeration value="MISS NOSE"/>
 *     &lt;enumeration value="MISS R EAR"/>
 *     &lt;enumeration value="MISS R EYE"/>
 *     &lt;enumeration value="MOLE CHIN"/>
 *     &lt;enumeration value="MOLE CHK"/>
 *     &lt;enumeration value="MOLE EAR"/>
 *     &lt;enumeration value="MOLE EYE"/>
 *     &lt;enumeration value="MOLE FACE"/>
 *     &lt;enumeration value="MOLE FHD"/>
 *     &lt;enumeration value="MOLE L CHK"/>
 *     &lt;enumeration value="MOLE L EAR"/>
 *     &lt;enumeration value="MOLE L EYE"/>
 *     &lt;enumeration value="MOLE LIP"/>
 *     &lt;enumeration value="MOLE L LIP"/>
 *     &lt;enumeration value="MOLE NOSE"/>
 *     &lt;enumeration value="MOLE R CHK"/>
 *     &lt;enumeration value="MOLE R EAR"/>
 *     &lt;enumeration value="MOLE R EYE"/>
 *     &lt;enumeration value="MOLE U LIP"/>
 *     &lt;enumeration value="MOUSTACHE"/>
 *     &lt;enumeration value="MOUTH OPEN"/>
 *     &lt;enumeration value="NEUTRAL"/>
 *     &lt;enumeration value="NO EAR"/>
 *     &lt;enumeration value="PRCD CHIN"/>
 *     &lt;enumeration value="PRCD EAR"/>
 *     &lt;enumeration value="PRCD EARS"/>
 *     &lt;enumeration value="PRCD EYE"/>
 *     &lt;enumeration value="PRCD L EAR"/>
 *     &lt;enumeration value="PRCD L EYE"/>
 *     &lt;enumeration value="PRCD LIP"/>
 *     &lt;enumeration value="PRCD LLIP"/>
 *     &lt;enumeration value="PRCD NOSE"/>
 *     &lt;enumeration value="PRCD R EAR"/>
 *     &lt;enumeration value="PRCD R EYE"/>
 *     &lt;enumeration value="PRCD ULIP"/>
 *     &lt;enumeration value="PROT JAW"/>
 *     &lt;enumeration value="PROT L JAW"/>
 *     &lt;enumeration value="PROT U JAW"/>
 *     &lt;enumeration value="RAISED BROWS"/>
 *     &lt;enumeration value="RIGHT EYE PATCH"/>
 *     &lt;enumeration value="RTAT CHEEK"/>
 *     &lt;enumeration value="RTAT CHIN"/>
 *     &lt;enumeration value="RTAT EAR"/>
 *     &lt;enumeration value="RTAT EYE"/>
 *     &lt;enumeration value="RTAT L CHK"/>
 *     &lt;enumeration value="RTAT L EAR"/>
 *     &lt;enumeration value="RTAT L EYE"/>
 *     &lt;enumeration value="RTAT LIP"/>
 *     &lt;enumeration value="RTAT LWLIP"/>
 *     &lt;enumeration value="RTAT LWRS"/>
 *     &lt;enumeration value="RTAT NOSE"/>
 *     &lt;enumeration value="RTAT R CHK"/>
 *     &lt;enumeration value="RTAT R EAR"/>
 *     &lt;enumeration value="RTAT R EYE"/>
 *     &lt;enumeration value="RTAT UPLIP"/>
 *     &lt;enumeration value="SCARF"/>
 *     &lt;enumeration value="SC CHIN"/>
 *     &lt;enumeration value="SC CHK"/>
 *     &lt;enumeration value="SC EAR"/>
 *     &lt;enumeration value="SC EYE"/>
 *     &lt;enumeration value="SC FHD"/>
 *     &lt;enumeration value="SC L CHK"/>
 *     &lt;enumeration value="SC L EAR"/>
 *     &lt;enumeration value="SC L EYE"/>
 *     &lt;enumeration value="SC LIP"/>
 *     &lt;enumeration value="SC LOW LIP"/>
 *     &lt;enumeration value="SC NOSE"/>
 *     &lt;enumeration value="SC R CHK"/>
 *     &lt;enumeration value="SC R EAR"/>
 *     &lt;enumeration value="SC R EYE"/>
 *     &lt;enumeration value="SC UP LIP"/>
 *     &lt;enumeration value="SLVR TOOTH"/>
 *     &lt;enumeration value="SMILE"/>
 *     &lt;enumeration value="SQUINTING"/>
 *     &lt;enumeration value="TAT CHEEK"/>
 *     &lt;enumeration value="TAT CHIN"/>
 *     &lt;enumeration value="TAT EAR"/>
 *     &lt;enumeration value="TAT EYE"/>
 *     &lt;enumeration value="TAT FHD"/>
 *     &lt;enumeration value="TAT L CHK"/>
 *     &lt;enumeration value="TAT L EAR"/>
 *     &lt;enumeration value="TAT L EYE"/>
 *     &lt;enumeration value="TAT LIP"/>
 *     &lt;enumeration value="TAT LW LIP"/>
 *     &lt;enumeration value="TAT NOSE"/>
 *     &lt;enumeration value="TAT R CHK"/>
 *     &lt;enumeration value="TAT R EAR"/>
 *     &lt;enumeration value="TAT R EYE"/>
 *     &lt;enumeration value="TAT UP LIP"/>
 *     &lt;enumeration value="TEETH VISIBLE"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FaceImageDescriptionCodeSimpleType")
@XmlEnum
public enum FaceImageDescriptionCodeSimpleType {


    /**
     * Ear, nonspecific, artificial
     * 
     */
    @XmlEnumValue("ART EAR")
    ART_EAR("ART EAR"),

    /**
     * Eye, nonspecific, artificial
     * 
     */
    @XmlEnumValue("ART EYE")
    ART_EYE("ART EYE"),

    /**
     * Ear, left, artificial
     * 
     */
    @XmlEnumValue("ART L EAR")
    ART_L_EAR("ART L EAR"),

    /**
     * Eye, left, artificial
     * 
     */
    @XmlEnumValue("ART L EYE")
    ART_L_EYE("ART L EYE"),

    /**
     * Ear, right, artificial
     * 
     */
    @XmlEnumValue("ART R EAR")
    ART_R_EAR("ART R EAR"),

    /**
     * Eye, right, artificial
     * 
     */
    @XmlEnumValue("ART R EYE")
    ART_R_EYE("ART R EYE"),

    /**
     * Bald/balding
     * 
     */
    BALD("BALD"),

    /**
     * Having beard
     * 
     */
    BEARD("BEARD"),

    /**
     * Blind, both eyes
     * 
     */
    BLIND("BLIND"),

    /**
     * Blinking (either or both eyes closed)
     * 
     */
    BLINK("BLINK"),

    /**
     * Blind, one eye, nonspecific
     * 
     */
    @XmlEnumValue("BLND EYE")
    BLND_EYE("BLND EYE"),

    /**
     * Blind, left eye
     * 
     */
    @XmlEnumValue("BLND L EYE")
    BLND_L_EYE("BLND L EYE"),

    /**
     * Blind, right eye
     * 
     */
    @XmlEnumValue("BLND R EYE")
    BLND_R_EYE("BLND R EYE"),

    /**
     * Braces, teeth
     * 
     */
    @XmlEnumValue("BRAC TEETH")
    BRAC_TEETH("BRAC TEETH"),

    /**
     * Cataract, left eye
     * 
     */
    @XmlEnumValue("CATA L EYE")
    CATA_L_EYE("CATA L EYE"),

    /**
     * Cataract, (nonspecific)
     * 
     */
    CATARACT("CATARACT"),

    /**
     * Cataract, right eye
     * 
     */
    @XmlEnumValue("CATA R EYE")
    CATA_R_EYE("CATA R EYE"),

    /**
     * Cauliflower ear, left
     * 
     */
    @XmlEnumValue("CAUL L EAR")
    CAUL_L_EAR("CAUL L EAR"),

    /**
     * Cauliflower ear, right
     * 
     */
    @XmlEnumValue("CAUL R EAR")
    CAUL_R_EAR("CAUL R EAR"),

    /**
     * Subject wearing clear glasses
     * 
     */
    @XmlEnumValue("CLEAR GLASSES")
    CLEAR_GLASSES("CLEAR GLASSES"),

    /**
     * Cleft chin
     * 
     */
    @XmlEnumValue("CLEFT CHIN")
    CLEFT_CHIN("CLEFT CHIN"),

    /**
     * Cleft lip
     * 
     */
    @XmlEnumValue("CL LIP")
    CL_LIP("CL LIP"),

    /**
     * Contact lenses
     * 
     */
    @XmlEnumValue("CON LENSES")
    CON_LENSES("CON LENSES"),

    /**
     * Cross-eyed
     * 
     */
    CROSSEYED("CROSSEYED"),

    /**
     * Subject wearing dark or visible colored glasses (medical)
     * 
     */
    @XmlEnumValue("DARK GLASSES")
    DARK_GLASSES("DARK GLASSES"),

    /**
     * Denture, lower only
     * 
     */
    @XmlEnumValue("DENT LOW")
    DENT_LOW("DENT LOW"),

    /**
     * Denture, upper only
     * 
     */
    @XmlEnumValue("DENT UP")
    DENT_UP("DENT UP"),

    /**
     * Denture, upper and lower
     * 
     */
    @XmlEnumValue("DENT UP LO")
    DENT_UP_LO("DENT UP LO"),

    /**
     * Cheek, nonspecific, dimple
     * 
     */
    @XmlEnumValue("DIMP CHEEK")
    DIMP_CHEEK("DIMP CHEEK"),

    /**
     * Dimple, chin
     * 
     */
    @XmlEnumValue("DIMP CHIN")
    DIMP_CHIN("DIMP CHIN"),

    /**
     * Face, dimple
     * 
     */
    @XmlEnumValue("DIMP FACE")
    DIMP_FACE("DIMP FACE"),

    /**
     * Dimples, left cheek (face)
     * 
     */
    @XmlEnumValue("DIMP L CHK")
    DIMP_L_CHK("DIMP L CHK"),

    /**
     * Dimples, right cheek (face)
     * 
     */
    @XmlEnumValue("DIMP R CHK")
    DIMP_R_CHK("DIMP R CHK"),

    /**
     * Cheek (face), nonspecific
     * 
     */
    @XmlEnumValue("DISC CHEEK")
    DISC_CHEEK("DISC CHEEK"),

    /**
     * Chin
     * 
     */
    @XmlEnumValue("DISC CHIN")
    DISC_CHIN("DISC CHIN"),

    /**
     * Ear, nonspecific
     * 
     */
    @XmlEnumValue("DISC EAR")
    DISC_EAR("DISC EAR"),

    /**
     * Eyebrow, nonspecific
     * 
     */
    @XmlEnumValue("DISC EYE")
    DISC_EYE("DISC EYE"),

    /**
     * Face, nonspecific
     * 
     */
    @XmlEnumValue("DISC FACE")
    DISC_FACE("DISC FACE"),

    /**
     * Forehead
     * 
     */
    @XmlEnumValue("DISC FHD")
    DISC_FHD("DISC FHD"),

    /**
     * Head
     * 
     */
    @XmlEnumValue("DISC HEAD")
    DISC_HEAD("DISC HEAD"),

    /**
     * Cheek (face), left
     * 
     */
    @XmlEnumValue("DISC L CHK")
    DISC_L_CHK("DISC L CHK"),

    /**
     * Ear, left
     * 
     */
    @XmlEnumValue("DISC L EAR")
    DISC_L_EAR("DISC L EAR"),

    /**
     * Eyebrow, left/left eye area
     * 
     */
    @XmlEnumValue("DISC L EYE")
    DISC_L_EYE("DISC L EYE"),

    /**
     * Lip, nonspecific
     * 
     */
    @XmlEnumValue("DISC LIP")
    DISC_LIP("DISC LIP"),

    /**
     * Lip, lower
     * 
     */
    @XmlEnumValue("DISC L LIP")
    DISC_L_LIP("DISC L LIP"),

    /**
     * Nose
     * 
     */
    @XmlEnumValue("DISC NOSE")
    DISC_NOSE("DISC NOSE"),

    /**
     * Cheek (face), right
     * 
     */
    @XmlEnumValue("DISC R CHK")
    DISC_R_CHK("DISC R CHK"),

    /**
     * Ear, right
     * 
     */
    @XmlEnumValue("DISC R EAR")
    DISC_R_EAR("DISC R EAR"),

    /**
     * Eyebrow, right/right eye area
     * 
     */
    @XmlEnumValue("DISC R EYE")
    DISC_R_EYE("DISC R EYE"),

    /**
     * Lip, upper
     * 
     */
    @XmlEnumValue("DISC U LIP")
    DISC_U_LIP("DISC U LIP"),

    /**
     * Having distorting medical condition impacting feature point detection
     * 
     */
    @XmlEnumValue("DISTORTING CONDITION")
    DISTORTING_CONDITION("DISTORTING CONDITION"),

    /**
     * Extra tooth/teeth (lower jaw)
     * 
     */
    @XmlEnumValue("EXTR L TTH")
    EXTR_L_TTH("EXTR L TTH"),

    /**
     * Extra tooth/teeth (upper jaw)
     * 
     */
    @XmlEnumValue("EXTR U TTH")
    EXTR_U_TTH("EXTR U TTH"),

    /**
     * Looking away from the camera
     * 
     */
    @XmlEnumValue("EYES AWAY")
    EYES_AWAY("EYES AWAY"),

    /**
     * Nose
     * 
     */
    @XmlEnumValue("FRC NOSE")
    FRC_NOSE("FRC NOSE"),

    /**
     * Jaw, upper left
     * 
     */
    @XmlEnumValue("FRC UL JAW")
    FRC_UL_JAW("FRC UL JAW"),

    /**
     * Jaw, upper right
     * 
     */
    @XmlEnumValue("FRC UR JAW")
    FRC_UR_JAW("FRC UR JAW"),

    /**
     * Freckles
     * 
     */
    FRECKLES("FRECKLES"),

    /**
     * Frowning
     * 
     */
    FROWNING("FROWNING"),

    /**
     * Glasses (prescription)
     * 
     */
    GLASSES("GLASSES"),

    /**
     * Gold tooth
     * 
     */
    @XmlEnumValue("GOLD TOOTH")
    GOLD_TOOTH("GOLD TOOTH"),

    /**
     * Head covering/hat
     * 
     */
    HAT("HAT"),

    /**
     * Subject wearing left eye patch
     * 
     */
    @XmlEnumValue("LEFT EYE PATCH")
    LEFT_EYE_PATCH("LEFT EYE PATCH"),

    /**
     * Acne
     * 
     */
    @XmlEnumValue("MC ACNE")
    MC_ACNE("MC ACNE"),

    /**
     * Ear, nonspecific, missing
     * 
     */
    @XmlEnumValue("MISS EAR")
    MISS_EAR("MISS EAR"),

    /**
     * Eye, nonspecific, missing
     * 
     */
    @XmlEnumValue("MISS EYE")
    MISS_EYE("MISS EYE"),

    /**
     * Ear, left
     * 
     */
    @XmlEnumValue("MISS L EAR")
    MISS_L_EAR("MISS L EAR"),

    /**
     * Eye, left
     * 
     */
    @XmlEnumValue("MISS L EYE")
    MISS_L_EYE("MISS L EYE"),

    /**
     * Nose
     * 
     */
    @XmlEnumValue("MISS NOSE")
    MISS_NOSE("MISS NOSE"),

    /**
     * Ear, right
     * 
     */
    @XmlEnumValue("MISS R EAR")
    MISS_R_EAR("MISS R EAR"),

    /**
     * Eye, right
     * 
     */
    @XmlEnumValue("MISS R EYE")
    MISS_R_EYE("MISS R EYE"),

    /**
     * Chin
     * 
     */
    @XmlEnumValue("MOLE CHIN")
    MOLE_CHIN("MOLE CHIN"),

    /**
     * Cheek (face), nonspecific
     * 
     */
    @XmlEnumValue("MOLE CHK")
    MOLE_CHK("MOLE CHK"),

    /**
     * Ear, nonspecific
     * 
     */
    @XmlEnumValue("MOLE EAR")
    MOLE_EAR("MOLE EAR"),

    /**
     * Eye, nonspecific, mole
     * 
     */
    @XmlEnumValue("MOLE EYE")
    MOLE_EYE("MOLE EYE"),

    /**
     * Face, mole
     * 
     */
    @XmlEnumValue("MOLE FACE")
    MOLE_FACE("MOLE FACE"),

    /**
     * Forehead
     * 
     */
    @XmlEnumValue("MOLE FHD")
    MOLE_FHD("MOLE FHD"),

    /**
     * Cheek (face), left
     * 
     */
    @XmlEnumValue("MOLE L CHK")
    MOLE_L_CHK("MOLE L CHK"),

    /**
     * Ear, left
     * 
     */
    @XmlEnumValue("MOLE L EAR")
    MOLE_L_EAR("MOLE L EAR"),

    /**
     * Eyebrow, left/left eye area
     * 
     */
    @XmlEnumValue("MOLE L EYE")
    MOLE_L_EYE("MOLE L EYE"),

    /**
     * Lip, nonspecific
     * 
     */
    @XmlEnumValue("MOLE LIP")
    MOLE_LIP("MOLE LIP"),

    /**
     * Lip, lower
     * 
     */
    @XmlEnumValue("MOLE L LIP")
    MOLE_L_LIP("MOLE L LIP"),

    /**
     * Nose
     * 
     */
    @XmlEnumValue("MOLE NOSE")
    MOLE_NOSE("MOLE NOSE"),

    /**
     * Cheek (face), right
     * 
     */
    @XmlEnumValue("MOLE R CHK")
    MOLE_R_CHK("MOLE R CHK"),

    /**
     * Ear, right
     * 
     */
    @XmlEnumValue("MOLE R EAR")
    MOLE_R_EAR("MOLE R EAR"),

    /**
     * Eyebrow, right/right eye area
     * 
     */
    @XmlEnumValue("MOLE R EYE")
    MOLE_R_EYE("MOLE R EYE"),

    /**
     * Lip, upper
     * 
     */
    @XmlEnumValue("MOLE U LIP")
    MOLE_U_LIP("MOLE U LIP"),

    /**
     * Having mustache
     * 
     */
    MOUSTACHE("MOUSTACHE"),

    /**
     * Subject having mouth open
     * 
     */
    @XmlEnumValue("MOUTH OPEN")
    MOUTH_OPEN("MOUTH OPEN"),

    /**
     * Neutral (non-smiling) with both eyes open and mouth closed
     * 
     */
    NEUTRAL("NEUTRAL"),

    /**
     * Ear(s) obscured by hair
     * 
     */
    @XmlEnumValue("NO EAR")
    NO_EAR("NO EAR"),

    /**
     * Pierced chin
     * 
     */
    @XmlEnumValue("PRCD CHIN")
    PRCD_CHIN("PRCD CHIN"),

    /**
     * Pierced ear, one, nonspecific
     * 
     */
    @XmlEnumValue("PRCD EAR")
    PRCD_EAR("PRCD EAR"),

    /**
     * Pierced ears
     * 
     */
    @XmlEnumValue("PRCD EARS")
    PRCD_EARS("PRCD EARS"),

    /**
     * Pierced eyebrow, nonspecific
     * 
     */
    @XmlEnumValue("PRCD EYE")
    PRCD_EYE("PRCD EYE"),

    /**
     * Pierced ear, left
     * 
     */
    @XmlEnumValue("PRCD L EAR")
    PRCD_L_EAR("PRCD L EAR"),

    /**
     * Pierced eyebrow, left
     * 
     */
    @XmlEnumValue("PRCD L EYE")
    PRCD_L_EYE("PRCD L EYE"),

    /**
     * Pierced lip, nonspecific
     * 
     */
    @XmlEnumValue("PRCD LIP")
    PRCD_LIP("PRCD LIP"),

    /**
     * Pierced lip, lower
     * 
     */
    @XmlEnumValue("PRCD LLIP")
    PRCD_LLIP("PRCD LLIP"),

    /**
     * Pierced nose
     * 
     */
    @XmlEnumValue("PRCD NOSE")
    PRCD_NOSE("PRCD NOSE"),

    /**
     * Pierced ear, right
     * 
     */
    @XmlEnumValue("PRCD R EAR")
    PRCD_R_EAR("PRCD R EAR"),

    /**
     * Pierced eyebrow, right
     * 
     */
    @XmlEnumValue("PRCD R EYE")
    PRCD_R_EYE("PRCD R EYE"),

    /**
     * Pierced lip, upper
     * 
     */
    @XmlEnumValue("PRCD ULIP")
    PRCD_ULIP("PRCD ULIP"),

    /**
     * Jaw, nonspecific, protruding
     * 
     */
    @XmlEnumValue("PROT JAW")
    PROT_JAW("PROT JAW"),

    /**
     * Protruding lower jaw
     * 
     */
    @XmlEnumValue("PROT L JAW")
    PROT_L_JAW("PROT L JAW"),

    /**
     * Protruding upper jaw
     * 
     */
    @XmlEnumValue("PROT U JAW")
    PROT_U_JAW("PROT U JAW"),

    /**
     * Raising eyebrows
     * 
     */
    @XmlEnumValue("RAISED BROWS")
    RAISED_BROWS("RAISED BROWS"),

    /**
     * Subject wearing right eye patch
     * 
     */
    @XmlEnumValue("RIGHT EYE PATCH")
    RIGHT_EYE_PATCH("RIGHT EYE PATCH"),

    /**
     * Cheek (face), nonspecific
     * 
     */
    @XmlEnumValue("RTAT CHEEK")
    RTAT_CHEEK("RTAT CHEEK"),

    /**
     * Chin
     * 
     */
    @XmlEnumValue("RTAT CHIN")
    RTAT_CHIN("RTAT CHIN"),

    /**
     * Ear, nonspecific
     * 
     */
    @XmlEnumValue("RTAT EAR")
    RTAT_EAR("RTAT EAR"),

    /**
     * Eye, nonspecific, remove tattoo
     * 
     */
    @XmlEnumValue("RTAT EYE")
    RTAT_EYE("RTAT EYE"),

    /**
     * Cheek (face), left
     * 
     */
    @XmlEnumValue("RTAT L CHK")
    RTAT_L_CHK("RTAT L CHK"),

    /**
     * Ear, left
     * 
     */
    @XmlEnumValue("RTAT L EAR")
    RTAT_L_EAR("RTAT L EAR"),

    /**
     * Left Eye, remove tattoo
     * 
     */
    @XmlEnumValue("RTAT L EYE")
    RTAT_L_EYE("RTAT L EYE"),

    /**
     * Lip, nonspecific
     * 
     */
    @XmlEnumValue("RTAT LIP")
    RTAT_LIP("RTAT LIP"),

    /**
     * Lip, lower
     * 
     */
    @XmlEnumValue("RTAT LWLIP")
    RTAT_LWLIP("RTAT LWLIP"),

    /**
     * Wrist, left
     * 
     */
    @XmlEnumValue("RTAT LWRS")
    RTAT_LWRS("RTAT LWRS"),

    /**
     * Nose
     * 
     */
    @XmlEnumValue("RTAT NOSE")
    RTAT_NOSE("RTAT NOSE"),

    /**
     * Cheek (face), right
     * 
     */
    @XmlEnumValue("RTAT R CHK")
    RTAT_R_CHK("RTAT R CHK"),

    /**
     * Ear, right
     * 
     */
    @XmlEnumValue("RTAT R EAR")
    RTAT_R_EAR("RTAT R EAR"),

    /**
     * Right Eye, remove tattoo
     * 
     */
    @XmlEnumValue("RTAT R EYE")
    RTAT_R_EYE("RTAT R EYE"),

    /**
     * Lip, upper
     * 
     */
    @XmlEnumValue("RTAT UPLIP")
    RTAT_UPLIP("RTAT UPLIP"),

    /**
     * Wearing scarf
     * 
     */
    SCARF("SCARF"),

    /**
     * Chin
     * 
     */
    @XmlEnumValue("SC CHIN")
    SC_CHIN("SC CHIN"),

    /**
     * Cheek (face), nonspecific
     * 
     */
    @XmlEnumValue("SC CHK")
    SC_CHK("SC CHK"),

    /**
     * Ear, nonspecific
     * 
     */
    @XmlEnumValue("SC EAR")
    SC_EAR("SC EAR"),

    /**
     * Eyebrow, nonspecific
     * 
     */
    @XmlEnumValue("SC EYE")
    SC_EYE("SC EYE"),

    /**
     * Forehead
     * 
     */
    @XmlEnumValue("SC FHD")
    SC_FHD("SC FHD"),

    /**
     * Cheek (face), left
     * 
     */
    @XmlEnumValue("SC L CHK")
    SC_L_CHK("SC L CHK"),

    /**
     * Ear, left
     * 
     */
    @XmlEnumValue("SC L EAR")
    SC_L_EAR("SC L EAR"),

    /**
     * Eyebrow, left/left eye area
     * 
     */
    @XmlEnumValue("SC L EYE")
    SC_L_EYE("SC L EYE"),

    /**
     * Lip, nonspecific
     * 
     */
    @XmlEnumValue("SC LIP")
    SC_LIP("SC LIP"),

    /**
     * Lip, lower
     * 
     */
    @XmlEnumValue("SC LOW LIP")
    SC_LOW_LIP("SC LOW LIP"),

    /**
     * Nose
     * 
     */
    @XmlEnumValue("SC NOSE")
    SC_NOSE("SC NOSE"),

    /**
     * Cheek (face), right
     * 
     */
    @XmlEnumValue("SC R CHK")
    SC_R_CHK("SC R CHK"),

    /**
     * Ear, right
     * 
     */
    @XmlEnumValue("SC R EAR")
    SC_R_EAR("SC R EAR"),

    /**
     * Eyebrow, right/right eye area
     * 
     */
    @XmlEnumValue("SC R EYE")
    SC_R_EYE("SC R EYE"),

    /**
     * Lip, upper
     * 
     */
    @XmlEnumValue("SC UP LIP")
    SC_UP_LIP("SC UP LIP"),

    /**
     * Silver tooth
     * 
     */
    @XmlEnumValue("SLVR TOOTH")
    SLVR_TOOTH("SLVR TOOTH"),

    /**
     * Smiling where the inside of the mouth and/or teeth is not exposed (closed jaw)
     * 
     */
    SMILE("SMILE"),

    /**
     * Squinting
     * 
     */
    SQUINTING("SQUINTING"),

    /**
     * Cheek (face), nonspecific
     * 
     */
    @XmlEnumValue("TAT CHEEK")
    TAT_CHEEK("TAT CHEEK"),

    /**
     * Chin
     * 
     */
    @XmlEnumValue("TAT CHIN")
    TAT_CHIN("TAT CHIN"),

    /**
     * Ear, nonspecific
     * 
     */
    @XmlEnumValue("TAT EAR")
    TAT_EAR("TAT EAR"),

    /**
     * Eye, nonspecific
     * 
     */
    @XmlEnumValue("TAT EYE")
    TAT_EYE("TAT EYE"),

    /**
     * Forehead
     * 
     */
    @XmlEnumValue("TAT FHD")
    TAT_FHD("TAT FHD"),

    /**
     * Cheek (face), left
     * 
     */
    @XmlEnumValue("TAT L CHK")
    TAT_L_CHK("TAT L CHK"),

    /**
     * Ear, left
     * 
     */
    @XmlEnumValue("TAT L EAR")
    TAT_L_EAR("TAT L EAR"),

    /**
     * Eye, left
     * 
     */
    @XmlEnumValue("TAT L EYE")
    TAT_L_EYE("TAT L EYE"),

    /**
     * Lip, nonspecific
     * 
     */
    @XmlEnumValue("TAT LIP")
    TAT_LIP("TAT LIP"),

    /**
     * Lip, lower
     * 
     */
    @XmlEnumValue("TAT LW LIP")
    TAT_LW_LIP("TAT LW LIP"),

    /**
     * Nose
     * 
     */
    @XmlEnumValue("TAT NOSE")
    TAT_NOSE("TAT NOSE"),

    /**
     * Cheek (face), right
     * 
     */
    @XmlEnumValue("TAT R CHK")
    TAT_R_CHK("TAT R CHK"),

    /**
     * Ear, right
     * 
     */
    @XmlEnumValue("TAT R EAR")
    TAT_R_EAR("TAT R EAR"),

    /**
     * Eye, right
     * 
     */
    @XmlEnumValue("TAT R EYE")
    TAT_R_EYE("TAT R EYE"),

    /**
     * Lip, upper
     * 
     */
    @XmlEnumValue("TAT UP LIP")
    TAT_UP_LIP("TAT UP LIP"),

    /**
     * Having teeth visible
     * 
     */
    @XmlEnumValue("TEETH VISIBLE")
    TEETH_VISIBLE("TEETH VISIBLE"),

    /**
     * Expression unspecified
     * 
     */
    UNKNOWN("UNKNOWN");
    private final String value;

    FaceImageDescriptionCodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FaceImageDescriptionCodeSimpleType fromValue(String v) {
        for (FaceImageDescriptionCodeSimpleType c: FaceImageDescriptionCodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
