//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for an image of a human face
 * 
 * <p>Java class for FaceImageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FaceImageType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/domains/biometrics/3.0/}ImageType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}FaceImageDescription" maxOccurs="50" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonEyeColor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "FaceImageType", propOrder = {
    "faceImageDescription",
    "personEyeColor"
})
public class FaceImageType
    extends ImageType
{

    @XmlElementRef(name = "FaceImageDescription", namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> faceImageDescription;
    @XmlElement(name = "PersonEyeColor", namespace = "http://release.niem.gov/niem/niem-core/3.0/")
    protected List<Object> personEyeColor;

    /**
     * Gets the value of the faceImageDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faceImageDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaceImageDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link FaceImageDescriptionCodeType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getFaceImageDescription() {
        if (faceImageDescription == null) {
            faceImageDescription = new ArrayList<JAXBElement<?>>();
        }
        return this.faceImageDescription;
    }

    /**
     * Gets the value of the personEyeColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personEyeColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonEyeColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPersonEyeColor() {
        if (personEyeColor == null) {
            personEyeColor = new ArrayList<Object>();
        }
        return this.personEyeColor;
    }

}
