//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.structures._3.ObjectType;


/**
 * A data type for a list of finger positions
 * 
 * <p>Java class for FingerprintPositionListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FingerprintPositionListType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}ObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}FingerPositionCode" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "FingerprintPositionListType", propOrder = {
    "fingerPositionCode"
})
public class FingerprintPositionListType
    extends ObjectType
{

    @XmlElement(name = "FingerPositionCode", nillable = true)
    protected FingerPositionCodeType fingerPositionCode;

    /**
     * Gets the value of the fingerPositionCode property.
     * 
     * @return
     *     possible object is
     *     {@link FingerPositionCodeType }
     *     
     */
    public FingerPositionCodeType getFingerPositionCode() {
        return fingerPositionCode;
    }

    /**
     * Sets the value of the fingerPositionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FingerPositionCodeType }
     *     
     */
    public void setFingerPositionCode(FingerPositionCodeType value) {
        this.fingerPositionCode = value;
    }

}
