//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.proxy.xsd._3.NonNegativeInteger;
import gov.niem.release.niem.structures._3.ObjectType;


/**
 * A data type for coordinates of the bounding box for an individual finger.
 * 
 * <p>Java class for FingerprintCoordinateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FingerprintCoordinateType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}ObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}SegmentTopVerticalCoordinateValue" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}SegmentLeftHorizontalCoordinateValue" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}SegmentRightHorizontalCoordinateValue" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}SegmentBottomVerticalCoordinateValue" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "FingerprintCoordinateType", propOrder = {
    "segmentTopVerticalCoordinateValue",
    "segmentLeftHorizontalCoordinateValue",
    "segmentRightHorizontalCoordinateValue",
    "segmentBottomVerticalCoordinateValue"
})
public class FingerprintCoordinateType
    extends ObjectType
{

    @XmlElement(name = "SegmentTopVerticalCoordinateValue", nillable = true)
    protected NonNegativeInteger segmentTopVerticalCoordinateValue;
    @XmlElement(name = "SegmentLeftHorizontalCoordinateValue", nillable = true)
    protected NonNegativeInteger segmentLeftHorizontalCoordinateValue;
    @XmlElement(name = "SegmentRightHorizontalCoordinateValue", nillable = true)
    protected NonNegativeInteger segmentRightHorizontalCoordinateValue;
    @XmlElement(name = "SegmentBottomVerticalCoordinateValue", nillable = true)
    protected NonNegativeInteger segmentBottomVerticalCoordinateValue;

    /**
     * Gets the value of the segmentTopVerticalCoordinateValue property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger }
     *     
     */
    public NonNegativeInteger getSegmentTopVerticalCoordinateValue() {
        return segmentTopVerticalCoordinateValue;
    }

    /**
     * Sets the value of the segmentTopVerticalCoordinateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger }
     *     
     */
    public void setSegmentTopVerticalCoordinateValue(NonNegativeInteger value) {
        this.segmentTopVerticalCoordinateValue = value;
    }

    /**
     * Gets the value of the segmentLeftHorizontalCoordinateValue property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger }
     *     
     */
    public NonNegativeInteger getSegmentLeftHorizontalCoordinateValue() {
        return segmentLeftHorizontalCoordinateValue;
    }

    /**
     * Sets the value of the segmentLeftHorizontalCoordinateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger }
     *     
     */
    public void setSegmentLeftHorizontalCoordinateValue(NonNegativeInteger value) {
        this.segmentLeftHorizontalCoordinateValue = value;
    }

    /**
     * Gets the value of the segmentRightHorizontalCoordinateValue property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger }
     *     
     */
    public NonNegativeInteger getSegmentRightHorizontalCoordinateValue() {
        return segmentRightHorizontalCoordinateValue;
    }

    /**
     * Sets the value of the segmentRightHorizontalCoordinateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger }
     *     
     */
    public void setSegmentRightHorizontalCoordinateValue(NonNegativeInteger value) {
        this.segmentRightHorizontalCoordinateValue = value;
    }

    /**
     * Gets the value of the segmentBottomVerticalCoordinateValue property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger }
     *     
     */
    public NonNegativeInteger getSegmentBottomVerticalCoordinateValue() {
        return segmentBottomVerticalCoordinateValue;
    }

    /**
     * Sets the value of the segmentBottomVerticalCoordinateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger }
     *     
     */
    public void setSegmentBottomVerticalCoordinateValue(NonNegativeInteger value) {
        this.segmentBottomVerticalCoordinateValue = value;
    }

}
