//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for a fingerprint image
 * 
 * <p>Java class for FingerprintImageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FingerprintImageType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/domains/biometrics/3.0/}ImageType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}FingerprintImagePosition" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "FingerprintImageType", propOrder = {
    "fingerprintImagePosition"
})
@XmlSeeAlso({
    com.creatrixinc.biometrix.xsd.biometrix.FingerprintImageType.class
})
public class FingerprintImageType
    extends ImageType
{

    @XmlElement(name = "FingerprintImagePosition", nillable = true)
    protected FingerprintPositionListType fingerprintImagePosition;

    /**
     * Gets the value of the fingerprintImagePosition property.
     * 
     * @return
     *     possible object is
     *     {@link FingerprintPositionListType }
     *     
     */
    public FingerprintPositionListType getFingerprintImagePosition() {
        return fingerprintImagePosition;
    }

    /**
     * Sets the value of the fingerprintImagePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link FingerprintPositionListType }
     *     
     */
    public void setFingerprintImagePosition(FingerprintPositionListType value) {
        this.fingerprintImagePosition = value;
    }

}
