//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IrisMissingCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IrisMissingCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="X"/>
 *     &lt;enumeration value="Z"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IrisMissingCodeSimpleType")
@XmlEnum
public enum IrisMissingCodeSimpleType {


    /**
     * Both eyes missing
     * 
     */
    A,

    /**
     * Not possible to capture either iris
     * 
     */
    B,

    /**
     * Not possible to capture left iris
     * 
     */
    L,

    /**
     * Not possible to capture right iris
     * 
     */
    R,

    /**
     * Right eye missing
     * 
     */
    X,

    /**
     * Left eye missing
     * 
     */
    Z;

    public String value() {
        return name();
    }

    public static IrisMissingCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
