//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.domains.biometrics._3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import gov.niem.release.niem.proxy.xsd._3.Integer;
import gov.niem.release.niem.proxy.xsd._3.NonNegativeInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niem.release.niem.domains.biometrics._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PosePitchAngleMeasure_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "PosePitchAngleMeasure");
    private final static QName _FingerprintImage_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FingerprintImage");
    private final static QName _BiometricImage_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "BiometricImage");
    private final static QName _FingerprintImageFingerMissing_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FingerprintImageFingerMissing");
    private final static QName _BiometricClassification_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "BiometricClassification");
    private final static QName _SegmentRightHorizontalCoordinateValue_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "SegmentRightHorizontalCoordinateValue");
    private final static QName _PoseRollAngleMeasure_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "PoseRollAngleMeasure");
    private final static QName _FaceImageDescription_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FaceImageDescription");
    private final static QName _FaceImageDescriptionCode_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FaceImageDescriptionCode");
    private final static QName _PoseAngleAugmentationPoint_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "PoseAngleAugmentationPoint");
    private final static QName _FingerprintImageSegmentPositionSquare_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FingerprintImageSegmentPositionSquare");
    private final static QName _BiometricDetail_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "BiometricDetail");
    private final static QName _Minutiae_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "Minutiae");
    private final static QName _IrisMissingCode_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "IrisMissingCode");
    private final static QName _SegmentLeftHorizontalCoordinateValue_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "SegmentLeftHorizontalCoordinateValue");
    private final static QName _SegmentBottomVerticalCoordinateValue_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "SegmentBottomVerticalCoordinateValue");
    private final static QName _PoseYawUncertaintyValue_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "PoseYawUncertaintyValue");
    private final static QName _PoseRollUncertaintyValue_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "PoseRollUncertaintyValue");
    private final static QName _BiometricClassificationCategoryCode_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "BiometricClassificationCategoryCode");
    private final static QName _IrisImage_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "IrisImage");
    private final static QName _FaceImage_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FaceImage");
    private final static QName _FingerprintImagePosition_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FingerprintImagePosition");
    private final static QName _PoseYawAngleMeasure_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "PoseYawAngleMeasure");
    private final static QName _PosePitchUncertaintyValue_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "PosePitchUncertaintyValue");
    private final static QName _FingerPositionCode_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FingerPositionCode");
    private final static QName _IrisEyePositionCode_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "IrisEyePositionCode");
    private final static QName _SegmentTopVerticalCoordinateValue_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "SegmentTopVerticalCoordinateValue");
    private final static QName _FingerprintCoordinate_QNAME = new QName("http://release.niem.gov/niem/domains/biometrics/3.0/", "FingerprintCoordinate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niem.release.niem.domains.biometrics._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BiometricCategoryCodeType }
     * 
     */
    public BiometricCategoryCodeType createBiometricCategoryCodeType() {
        return new BiometricCategoryCodeType();
    }

    /**
     * Create an instance of {@link IrisImageType }
     * 
     */
    public IrisImageType createIrisImageType() {
        return new IrisImageType();
    }

    /**
     * Create an instance of {@link FingerprintImageFingerMissingType }
     * 
     */
    public FingerprintImageFingerMissingType createFingerprintImageFingerMissingType() {
        return new FingerprintImageFingerMissingType();
    }

    /**
     * Create an instance of {@link BiometricClassificationType }
     * 
     */
    public BiometricClassificationType createBiometricClassificationType() {
        return new BiometricClassificationType();
    }

    /**
     * Create an instance of {@link FingerprintImageType }
     * 
     */
    public FingerprintImageType createFingerprintImageType() {
        return new FingerprintImageType();
    }

    /**
     * Create an instance of {@link MinutiaeType }
     * 
     */
    public MinutiaeType createMinutiaeType() {
        return new MinutiaeType();
    }

    /**
     * Create an instance of {@link IrisMissingCodeType }
     * 
     */
    public IrisMissingCodeType createIrisMissingCodeType() {
        return new IrisMissingCodeType();
    }

    /**
     * Create an instance of {@link EyePositionCodeType }
     * 
     */
    public EyePositionCodeType createEyePositionCodeType() {
        return new EyePositionCodeType();
    }

    /**
     * Create an instance of {@link FingerprintCoordinateType }
     * 
     */
    public FingerprintCoordinateType createFingerprintCoordinateType() {
        return new FingerprintCoordinateType();
    }

    /**
     * Create an instance of {@link FingerprintImageSegmentPositionSquareType }
     * 
     */
    public FingerprintImageSegmentPositionSquareType createFingerprintImageSegmentPositionSquareType() {
        return new FingerprintImageSegmentPositionSquareType();
    }

    /**
     * Create an instance of {@link FingerprintPositionListType }
     * 
     */
    public FingerprintPositionListType createFingerprintPositionListType() {
        return new FingerprintPositionListType();
    }

    /**
     * Create an instance of {@link FingerPositionCodeType }
     * 
     */
    public FingerPositionCodeType createFingerPositionCodeType() {
        return new FingerPositionCodeType();
    }

    /**
     * Create an instance of {@link FaceImageDescriptionCodeType }
     * 
     */
    public FaceImageDescriptionCodeType createFaceImageDescriptionCodeType() {
        return new FaceImageDescriptionCodeType();
    }

    /**
     * Create an instance of {@link FaceImageType }
     * 
     */
    public FaceImageType createFaceImageType() {
        return new FaceImageType();
    }

    /**
     * Create an instance of {@link PoseAngleType }
     * 
     */
    public PoseAngleType createPoseAngleType() {
        return new PoseAngleType();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link BiometricDataType }
     * 
     */
    public BiometricDataType createBiometricDataType() {
        return new BiometricDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "PosePitchAngleMeasure")
    public JAXBElement<Integer> createPosePitchAngleMeasure(Integer value) {
        return new JAXBElement<Integer>(_PosePitchAngleMeasure_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintImageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FingerprintImage", substitutionHeadNamespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", substitutionHeadName = "BiometricImage")
    public JAXBElement<FingerprintImageType> createFingerprintImage(FingerprintImageType value) {
        return new JAXBElement<FingerprintImageType>(_FingerprintImage_QNAME, FingerprintImageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "BiometricImage")
    public JAXBElement<Object> createBiometricImage(Object value) {
        return new JAXBElement<Object>(_BiometricImage_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintImageFingerMissingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FingerprintImageFingerMissing")
    public JAXBElement<FingerprintImageFingerMissingType> createFingerprintImageFingerMissing(FingerprintImageFingerMissingType value) {
        return new JAXBElement<FingerprintImageFingerMissingType>(_FingerprintImageFingerMissing_QNAME, FingerprintImageFingerMissingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiometricClassificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "BiometricClassification")
    public JAXBElement<BiometricClassificationType> createBiometricClassification(BiometricClassificationType value) {
        return new JAXBElement<BiometricClassificationType>(_BiometricClassification_QNAME, BiometricClassificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "SegmentRightHorizontalCoordinateValue")
    public JAXBElement<NonNegativeInteger> createSegmentRightHorizontalCoordinateValue(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_SegmentRightHorizontalCoordinateValue_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "PoseRollAngleMeasure")
    public JAXBElement<Integer> createPoseRollAngleMeasure(Integer value) {
        return new JAXBElement<Integer>(_PoseRollAngleMeasure_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FaceImageDescription")
    public JAXBElement<Object> createFaceImageDescription(Object value) {
        return new JAXBElement<Object>(_FaceImageDescription_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaceImageDescriptionCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FaceImageDescriptionCode", substitutionHeadNamespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", substitutionHeadName = "FaceImageDescription")
    public JAXBElement<FaceImageDescriptionCodeType> createFaceImageDescriptionCode(FaceImageDescriptionCodeType value) {
        return new JAXBElement<FaceImageDescriptionCodeType>(_FaceImageDescriptionCode_QNAME, FaceImageDescriptionCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "PoseAngleAugmentationPoint")
    public JAXBElement<Object> createPoseAngleAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_PoseAngleAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintImageSegmentPositionSquareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FingerprintImageSegmentPositionSquare")
    public JAXBElement<FingerprintImageSegmentPositionSquareType> createFingerprintImageSegmentPositionSquare(FingerprintImageSegmentPositionSquareType value) {
        return new JAXBElement<FingerprintImageSegmentPositionSquareType>(_FingerprintImageSegmentPositionSquare_QNAME, FingerprintImageSegmentPositionSquareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "BiometricDetail")
    public JAXBElement<Object> createBiometricDetail(Object value) {
        return new JAXBElement<Object>(_BiometricDetail_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MinutiaeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "Minutiae", substitutionHeadNamespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", substitutionHeadName = "BiometricDetail")
    public JAXBElement<MinutiaeType> createMinutiae(MinutiaeType value) {
        return new JAXBElement<MinutiaeType>(_Minutiae_QNAME, MinutiaeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IrisMissingCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "IrisMissingCode")
    public JAXBElement<IrisMissingCodeType> createIrisMissingCode(IrisMissingCodeType value) {
        return new JAXBElement<IrisMissingCodeType>(_IrisMissingCode_QNAME, IrisMissingCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "SegmentLeftHorizontalCoordinateValue")
    public JAXBElement<NonNegativeInteger> createSegmentLeftHorizontalCoordinateValue(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_SegmentLeftHorizontalCoordinateValue_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "SegmentBottomVerticalCoordinateValue")
    public JAXBElement<NonNegativeInteger> createSegmentBottomVerticalCoordinateValue(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_SegmentBottomVerticalCoordinateValue_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "PoseYawUncertaintyValue")
    public JAXBElement<NonNegativeInteger> createPoseYawUncertaintyValue(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_PoseYawUncertaintyValue_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "PoseRollUncertaintyValue")
    public JAXBElement<NonNegativeInteger> createPoseRollUncertaintyValue(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_PoseRollUncertaintyValue_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiometricCategoryCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "BiometricClassificationCategoryCode")
    public JAXBElement<BiometricCategoryCodeType> createBiometricClassificationCategoryCode(BiometricCategoryCodeType value) {
        return new JAXBElement<BiometricCategoryCodeType>(_BiometricClassificationCategoryCode_QNAME, BiometricCategoryCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IrisImageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "IrisImage", substitutionHeadNamespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", substitutionHeadName = "BiometricImage")
    public JAXBElement<IrisImageType> createIrisImage(IrisImageType value) {
        return new JAXBElement<IrisImageType>(_IrisImage_QNAME, IrisImageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaceImageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FaceImage", substitutionHeadNamespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", substitutionHeadName = "BiometricImage")
    public JAXBElement<FaceImageType> createFaceImage(FaceImageType value) {
        return new JAXBElement<FaceImageType>(_FaceImage_QNAME, FaceImageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintPositionListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FingerprintImagePosition")
    public JAXBElement<FingerprintPositionListType> createFingerprintImagePosition(FingerprintPositionListType value) {
        return new JAXBElement<FingerprintPositionListType>(_FingerprintImagePosition_QNAME, FingerprintPositionListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "PoseYawAngleMeasure")
    public JAXBElement<Integer> createPoseYawAngleMeasure(Integer value) {
        return new JAXBElement<Integer>(_PoseYawAngleMeasure_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "PosePitchUncertaintyValue")
    public JAXBElement<NonNegativeInteger> createPosePitchUncertaintyValue(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_PosePitchUncertaintyValue_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerPositionCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FingerPositionCode")
    public JAXBElement<FingerPositionCodeType> createFingerPositionCode(FingerPositionCodeType value) {
        return new JAXBElement<FingerPositionCodeType>(_FingerPositionCode_QNAME, FingerPositionCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EyePositionCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "IrisEyePositionCode")
    public JAXBElement<EyePositionCodeType> createIrisEyePositionCode(EyePositionCodeType value) {
        return new JAXBElement<EyePositionCodeType>(_IrisEyePositionCode_QNAME, EyePositionCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "SegmentTopVerticalCoordinateValue")
    public JAXBElement<NonNegativeInteger> createSegmentTopVerticalCoordinateValue(NonNegativeInteger value) {
        return new JAXBElement<NonNegativeInteger>(_SegmentTopVerticalCoordinateValue_QNAME, NonNegativeInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintCoordinateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", name = "FingerprintCoordinate")
    public JAXBElement<FingerprintCoordinateType> createFingerprintCoordinate(FingerprintCoordinateType value) {
        return new JAXBElement<FingerprintCoordinateType>(_FingerprintCoordinate_QNAME, FingerprintCoordinateType.class, null, value);
    }

}
