//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package com.creatrixinc.biometrix.xsd.biometrix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BiometrixResponsesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiometrixResponsesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="RequestId">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.creatrixinc.com/biometrix/xsd/biometrix}IdentificationType">
 *                 &lt;sequence>
 *                   &lt;sequence>
 *                     &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}IdentificationID"/>
 *                   &lt;/sequence>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CommandId" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}IdentificationType" minOccurs="0"/>
 *         &lt;element name="CommandType" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}CommandTypes"/>
 *         &lt;element name="CommandExecutionStatus" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}CommandExecutionStatus"/>
 *         &lt;element ref="{http://www.creatrixinc.com/biometrix/xsd/biometrix}BiometrixResponse" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "BiometrixResponsesType", propOrder = {
    "clientId",
    "requestId",
    "commandId",
    "commandType",
    "commandExecutionStatus",
    "biometrixResponse"
})
public class BiometrixResponsesType {

    @XmlElement(name = "ClientId", required = true)
    protected Object clientId;
    @XmlElement(name = "RequestId", required = true)
    protected BiometrixResponsesType.RequestId requestId;
    @XmlElement(name = "CommandId")
    protected IdentificationType commandId;
    @XmlElement(name = "CommandType", required = true)
    @XmlSchemaType(name = "string")
    protected CommandTypes commandType;
    @XmlElement(name = "CommandExecutionStatus", required = true)
    protected CommandExecutionStatus commandExecutionStatus;
    @XmlElement(name = "BiometrixResponse", required = true)
    protected List<BiometrixResponseType> biometrixResponse;

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setClientId(Object value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link BiometrixResponsesType.RequestId }
     *     
     */
    public BiometrixResponsesType.RequestId getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiometrixResponsesType.RequestId }
     *     
     */
    public void setRequestId(BiometrixResponsesType.RequestId value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the commandId property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationType }
     *     
     */
    public IdentificationType getCommandId() {
        return commandId;
    }

    /**
     * Sets the value of the commandId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationType }
     *     
     */
    public void setCommandId(IdentificationType value) {
        this.commandId = value;
    }

    /**
     * Gets the value of the commandType property.
     * 
     * @return
     *     possible object is
     *     {@link CommandTypes }
     *     
     */
    public CommandTypes getCommandType() {
        return commandType;
    }

    /**
     * Sets the value of the commandType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandTypes }
     *     
     */
    public void setCommandType(CommandTypes value) {
        this.commandType = value;
    }

    /**
     * Gets the value of the commandExecutionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CommandExecutionStatus }
     *     
     */
    public CommandExecutionStatus getCommandExecutionStatus() {
        return commandExecutionStatus;
    }

    /**
     * Sets the value of the commandExecutionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandExecutionStatus }
     *     
     */
    public void setCommandExecutionStatus(CommandExecutionStatus value) {
        this.commandExecutionStatus = value;
    }

    /**
     * Gets the value of the biometrixResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the biometrixResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBiometrixResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BiometrixResponseType }
     * 
     * 
     */
    public List<BiometrixResponseType> getBiometrixResponse() {
        if (biometrixResponse == null) {
            biometrixResponse = new ArrayList<BiometrixResponseType>();
        }
        return this.biometrixResponse;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.creatrixinc.com/biometrix/xsd/biometrix}IdentificationType">
     *       &lt;sequence>
     *         &lt;sequence>
     *           &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}IdentificationID"/>
     *         &lt;/sequence>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.PROPERTY)
    @XmlType(name = "")
    public static class RequestId
        extends IdentificationType
    {


    }

}
