//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package com.creatrixinc.biometrix.xsd.biometrix;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommandTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CommandTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ENROLL"/>
 *     &lt;enumeration value="IDENTIFY"/>
 *     &lt;enumeration value="VERIFY"/>
 *     &lt;enumeration value="GET_ENROLL_RESULT"/>
 *     &lt;enumeration value="GET_IDENTIFY_RESULT"/>
 *     &lt;enumeration value="GET_VERIFY_RESULT"/>
 *     &lt;enumeration value="GET_PERSON"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CommandTypes")
@XmlEnum
public enum CommandTypes {

    ENROLL,
    IDENTIFY,
    VERIFY,
    GET_ENROLL_RESULT,
    GET_IDENTIFY_RESULT,
    GET_VERIFY_RESULT,
    GET_PERSON;

    public String value() {
        return name();
    }

    public static CommandTypes fromValue(String v) {
        return valueOf(v);
    }

}
