//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package com.creatrixinc.biometrix.xsd.biometrix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommandExecutionStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommandExecutionStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CommandExecutionStatusCode" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}CommandExecutionStatusCode"/>
 *         &lt;element name="CommandExecutionStatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "CommandExecutionStatus", propOrder = {
    "commandExecutionStatusCode",
    "commandExecutionStatusMessage"
})
public class CommandExecutionStatus {

    @XmlElement(name = "CommandExecutionStatusCode", required = true)
    @XmlSchemaType(name = "string")
    protected CommandExecutionStatusCode commandExecutionStatusCode;
    @XmlElement(name = "CommandExecutionStatusMessage")
    protected String commandExecutionStatusMessage;

    /**
     * Gets the value of the commandExecutionStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link CommandExecutionStatusCode }
     *     
     */
    public CommandExecutionStatusCode getCommandExecutionStatusCode() {
        return commandExecutionStatusCode;
    }

    /**
     * Sets the value of the commandExecutionStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandExecutionStatusCode }
     *     
     */
    public void setCommandExecutionStatusCode(CommandExecutionStatusCode value) {
        this.commandExecutionStatusCode = value;
    }

    /**
     * Gets the value of the commandExecutionStatusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandExecutionStatusMessage() {
        return commandExecutionStatusMessage;
    }

    /**
     * Sets the value of the commandExecutionStatusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandExecutionStatusMessage(String value) {
        this.commandExecutionStatusMessage = value;
    }

}
