//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package com.creatrixinc.biometrix.xsd.biometrix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.domains.biometrics._3.BiometricClassificationType;
import gov.niem.release.niem.domains.biometrics._3.FingerprintImageType;
import gov.niem.release.niem.domains.biometrics._3.MinutiaeType;


/**
 * <p>Java class for FingerprintType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FingerprintType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}BiometricClassification"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}FingerprintImage"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/biometrics/3.0/}Minutiae"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "FingerprintType", propOrder = {
    "biometricClassification",
    "fingerprintImage",
    "minutiae"
})
public class FingerprintType {

    @XmlElement(name = "BiometricClassification", namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", required = true, nillable = true)
    protected BiometricClassificationType biometricClassification;
    @XmlElement(name = "FingerprintImage", namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", required = true)
    protected FingerprintImageType fingerprintImage;
    @XmlElement(name = "Minutiae", namespace = "http://release.niem.gov/niem/domains/biometrics/3.0/", required = true)
    protected MinutiaeType minutiae;

    /**
     * Gets the value of the biometricClassification property.
     * 
     * @return
     *     possible object is
     *     {@link BiometricClassificationType }
     *     
     */
    public BiometricClassificationType getBiometricClassification() {
        return biometricClassification;
    }

    /**
     * Sets the value of the biometricClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiometricClassificationType }
     *     
     */
    public void setBiometricClassification(BiometricClassificationType value) {
        this.biometricClassification = value;
    }

    /**
     * Gets the value of the fingerprintImage property.
     * 
     * @return
     *     possible object is
     *     {@link FingerprintImageType }
     *     
     */
    public FingerprintImageType getFingerprintImage() {
        return fingerprintImage;
    }

    /**
     * Sets the value of the fingerprintImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link FingerprintImageType }
     *     
     */
    public void setFingerprintImage(FingerprintImageType value) {
        this.fingerprintImage = value;
    }

    /**
     * Gets the value of the minutiae property.
     * 
     * @return
     *     possible object is
     *     {@link MinutiaeType }
     *     
     */
    public MinutiaeType getMinutiae() {
        return minutiae;
    }

    /**
     * Sets the value of the minutiae property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinutiaeType }
     *     
     */
    public void setMinutiae(MinutiaeType value) {
        this.minutiae = value;
    }

}
