//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package com.creatrixinc.biometrix.xsd.biometrix;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.niem_core._3.PersonNameTextType;


/**
 * <p>Java class for PersonNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonNameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonNameSquenceNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonGivenName"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonMiddleName"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonSurName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "PersonNameType", propOrder = {
    "personNameSquenceNumber",
    "personGivenName",
    "personMiddleName",
    "personSurName"
})
public class PersonNameType {

    @XmlElement(name = "PersonNameSquenceNumber", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger personNameSquenceNumber;
    @XmlElement(name = "PersonGivenName", namespace = "http://release.niem.gov/niem/niem-core/3.0/", required = true, nillable = true)
    protected PersonNameTextType personGivenName;
    @XmlElement(name = "PersonMiddleName", namespace = "http://release.niem.gov/niem/niem-core/3.0/", required = true, nillable = true)
    protected PersonNameTextType personMiddleName;
    @XmlElement(name = "PersonSurName", namespace = "http://release.niem.gov/niem/niem-core/3.0/", required = true, nillable = true)
    protected PersonNameTextType personSurName;

    /**
     * Gets the value of the personNameSquenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersonNameSquenceNumber() {
        return personNameSquenceNumber;
    }

    /**
     * Sets the value of the personNameSquenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersonNameSquenceNumber(BigInteger value) {
        this.personNameSquenceNumber = value;
    }

    /**
     * Gets the value of the personGivenName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameTextType }
     *     
     */
    public PersonNameTextType getPersonGivenName() {
        return personGivenName;
    }

    /**
     * Sets the value of the personGivenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameTextType }
     *     
     */
    public void setPersonGivenName(PersonNameTextType value) {
        this.personGivenName = value;
    }

    /**
     * Gets the value of the personMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameTextType }
     *     
     */
    public PersonNameTextType getPersonMiddleName() {
        return personMiddleName;
    }

    /**
     * Sets the value of the personMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameTextType }
     *     
     */
    public void setPersonMiddleName(PersonNameTextType value) {
        this.personMiddleName = value;
    }

    /**
     * Gets the value of the personSurName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameTextType }
     *     
     */
    public PersonNameTextType getPersonSurName() {
        return personSurName;
    }

    /**
     * Sets the value of the personSurName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameTextType }
     *     
     */
    public void setPersonSurName(PersonNameTextType value) {
        this.personSurName = value;
    }

}
