//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package com.creatrixinc.biometrix.xsd.biometrix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import gov.niem.release.niem.codes.fbi_ncic._3.EYECodeType;
import gov.niem.release.niem.codes.fbi_ncic._3.HAICodeType;
import gov.niem.release.niem.codes.fbi_ncic._3.SEXCodeType;
import gov.niem.release.niem.codes.iso_3166_1._3.CountryAlpha2CodeType;
import gov.niem.release.niem.niem_core._3.PersonNameType;


/**
 * <p>Java class for PersonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonId" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}IdentificationType"/>
 *         &lt;element name="PersonBirthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PersonCitizenship" type="{http://release.niem.gov/niem/codes/iso_3166-1/3.0/}CountryAlpha2CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonEyeColor" type="{http://release.niem.gov/niem/codes/fbi_ncic/3.0/}EYECodeType" minOccurs="0"/>
 *         &lt;element name="PersonHairColor" type="{http://release.niem.gov/niem/codes/fbi_ncic/3.0/}HAICodeType" minOccurs="0"/>
 *         &lt;element name="PersonHeightMeasure" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}HeightMeasureType" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonSex" type="{http://release.niem.gov/niem/codes/fbi_ncic/3.0/}SEXCodeType" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonSSNIdentification" minOccurs="0"/>
 *         &lt;element name="PersonWeightMeasure" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}WeightMeasureType" minOccurs="0"/>
 *         &lt;element name="FaceImage" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="FingerprintImage" type="{http://www.creatrixinc.com/biometrix/xsd/biometrix}FingerprintImageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "PersonType", propOrder = {
    "personId",
    "personBirthDate",
    "personCitizenship",
    "personEyeColor",
    "personHairColor",
    "personHeightMeasure",
    "personName",
    "personSex",
    "personSSNIdentification",
    "personWeightMeasure",
    "faceImage",
    "fingerprintImage"
})
@XmlSeeAlso({
    Person.class
})
public class PersonType {

    @XmlElement(name = "PersonId", required = true)
    protected com.creatrixinc.biometrix.xsd.biometrix.IdentificationType personId;
    @XmlElement(name = "PersonBirthDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar personBirthDate;
    @XmlElement(name = "PersonCitizenship")
    protected List<CountryAlpha2CodeType> personCitizenship;
    @XmlElement(name = "PersonEyeColor")
    protected EYECodeType personEyeColor;
    @XmlElement(name = "PersonHairColor")
    protected HAICodeType personHairColor;
    @XmlElement(name = "PersonHeightMeasure")
    protected HeightMeasureType personHeightMeasure;
    @XmlElement(name = "PersonName", namespace = "http://release.niem.gov/niem/niem-core/3.0/", nillable = true)
    protected List<PersonNameType> personName;
    @XmlElement(name = "PersonSex")
    protected SEXCodeType personSex;
    @XmlElement(name = "PersonSSNIdentification", namespace = "http://release.niem.gov/niem/niem-core/3.0/", nillable = true)
    protected gov.niem.release.niem.niem_core._3.IdentificationType personSSNIdentification;
    @XmlElement(name = "PersonWeightMeasure")
    protected WeightMeasureType personWeightMeasure;
    @XmlElement(name = "FaceImage")
    protected byte[] faceImage;
    @XmlElement(name = "FingerprintImage")
    protected List<FingerprintImageType> fingerprintImage;

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link com.creatrixinc.biometrix.xsd.biometrix.IdentificationType }
     *     
     */
    public com.creatrixinc.biometrix.xsd.biometrix.IdentificationType getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.creatrixinc.biometrix.xsd.biometrix.IdentificationType }
     *     
     */
    public void setPersonId(com.creatrixinc.biometrix.xsd.biometrix.IdentificationType value) {
        this.personId = value;
    }

    /**
     * Gets the value of the personBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPersonBirthDate() {
        return personBirthDate;
    }

    /**
     * Sets the value of the personBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPersonBirthDate(XMLGregorianCalendar value) {
        this.personBirthDate = value;
    }

    /**
     * Gets the value of the personCitizenship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personCitizenship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonCitizenship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryAlpha2CodeType }
     * 
     * 
     */
    public List<CountryAlpha2CodeType> getPersonCitizenship() {
        if (personCitizenship == null) {
            personCitizenship = new ArrayList<CountryAlpha2CodeType>();
        }
        return this.personCitizenship;
    }

    /**
     * Gets the value of the personEyeColor property.
     * 
     * @return
     *     possible object is
     *     {@link EYECodeType }
     *     
     */
    public EYECodeType getPersonEyeColor() {
        return personEyeColor;
    }

    /**
     * Sets the value of the personEyeColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link EYECodeType }
     *     
     */
    public void setPersonEyeColor(EYECodeType value) {
        this.personEyeColor = value;
    }

    /**
     * Gets the value of the personHairColor property.
     * 
     * @return
     *     possible object is
     *     {@link HAICodeType }
     *     
     */
    public HAICodeType getPersonHairColor() {
        return personHairColor;
    }

    /**
     * Sets the value of the personHairColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link HAICodeType }
     *     
     */
    public void setPersonHairColor(HAICodeType value) {
        this.personHairColor = value;
    }

    /**
     * Gets the value of the personHeightMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link HeightMeasureType }
     *     
     */
    public HeightMeasureType getPersonHeightMeasure() {
        return personHeightMeasure;
    }

    /**
     * Sets the value of the personHeightMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeightMeasureType }
     *     
     */
    public void setPersonHeightMeasure(HeightMeasureType value) {
        this.personHeightMeasure = value;
    }

    /**
     * Gets the value of the personName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonNameType }
     * 
     * 
     */
    public List<PersonNameType> getPersonName() {
        if (personName == null) {
            personName = new ArrayList<PersonNameType>();
        }
        return this.personName;
    }

    /**
     * Gets the value of the personSex property.
     * 
     * @return
     *     possible object is
     *     {@link SEXCodeType }
     *     
     */
    public SEXCodeType getPersonSex() {
        return personSex;
    }

    /**
     * Sets the value of the personSex property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEXCodeType }
     *     
     */
    public void setPersonSex(SEXCodeType value) {
        this.personSex = value;
    }

    /**
     * Gets the value of the personSSNIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link gov.niem.release.niem.niem_core._3.IdentificationType }
     *     
     */
    public gov.niem.release.niem.niem_core._3.IdentificationType getPersonSSNIdentification() {
        return personSSNIdentification;
    }

    /**
     * Sets the value of the personSSNIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link gov.niem.release.niem.niem_core._3.IdentificationType }
     *     
     */
    public void setPersonSSNIdentification(gov.niem.release.niem.niem_core._3.IdentificationType value) {
        this.personSSNIdentification = value;
    }

    /**
     * Gets the value of the personWeightMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link WeightMeasureType }
     *     
     */
    public WeightMeasureType getPersonWeightMeasure() {
        return personWeightMeasure;
    }

    /**
     * Sets the value of the personWeightMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightMeasureType }
     *     
     */
    public void setPersonWeightMeasure(WeightMeasureType value) {
        this.personWeightMeasure = value;
    }

    /**
     * Gets the value of the faceImage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFaceImage() {
        return faceImage;
    }

    /**
     * Sets the value of the faceImage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFaceImage(byte[] value) {
        this.faceImage = value;
    }

    /**
     * Gets the value of the fingerprintImage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fingerprintImage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFingerprintImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FingerprintImageType }
     * 
     * 
     */
    public List<FingerprintImageType> getFingerprintImage() {
        if (fingerprintImage == null) {
            fingerprintImage = new ArrayList<FingerprintImageType>();
        }
        return this.fingerprintImage;
    }

}
