//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.niem_core._3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for a name by which a person is known, referred, or addressed.
 * 
 * <p>Java class for PersonNameTextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonNameTextType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://release.niem.gov/niem/niem-core/3.0/>ProperNameTextType">
 *       &lt;attribute ref="{http://release.niem.gov/niem/niem-core/3.0/}personNameInitialIndicator"/>
 *       &lt;attribute ref="{http://release.niem.gov/niem/niem-core/3.0/}sequenceID"/>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "PersonNameTextType")
@XmlSeeAlso({
    com.creatrixinc.biometrix.xsd.biometrix.PersonNameTextType.class
})
public class PersonNameTextType
    extends ProperNameTextType
{

    @XmlAttribute(name = "personNameInitialIndicator", namespace = "http://release.niem.gov/niem/niem-core/3.0/")
    protected Boolean personNameInitialIndicator;
    @XmlAttribute(name = "sequenceID", namespace = "http://release.niem.gov/niem/niem-core/3.0/")
    protected BigInteger sequenceID;

    /**
     * Gets the value of the personNameInitialIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPersonNameInitialIndicator() {
        return personNameInitialIndicator;
    }

    /**
     * Sets the value of the personNameInitialIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPersonNameInitialIndicator(Boolean value) {
        this.personNameInitialIndicator = value;
    }

    /**
     * Gets the value of the sequenceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceID() {
        return sequenceID;
    }

    /**
     * Sets the value of the sequenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceID(BigInteger value) {
        this.sequenceID = value;
    }

}
