//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.niem_core._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.structures._3.ObjectType;


/**
 * A data type for a combination of names and/or titles by which a person is known.
 * 
 * <p>Java class for PersonNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonNameType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}ObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonGivenName" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonMiddleName" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonSurName" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/3.0/}PersonMaidenName" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "PersonNameType", propOrder = {
    "personGivenName",
    "personMiddleName",
    "personSurName",
    "personMaidenName"
})
public class PersonNameType
    extends ObjectType
{

    @XmlElement(name = "PersonGivenName", nillable = true)
    protected PersonNameTextType personGivenName;
    @XmlElement(name = "PersonMiddleName", nillable = true)
    protected PersonNameTextType personMiddleName;
    @XmlElement(name = "PersonSurName", nillable = true)
    protected PersonNameTextType personSurName;
    @XmlElement(name = "PersonMaidenName", nillable = true)
    protected PersonNameTextType personMaidenName;

    /**
     * Gets the value of the personGivenName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameTextType }
     *     
     */
    public PersonNameTextType getPersonGivenName() {
        return personGivenName;
    }

    /**
     * Sets the value of the personGivenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameTextType }
     *     
     */
    public void setPersonGivenName(PersonNameTextType value) {
        this.personGivenName = value;
    }

    /**
     * Gets the value of the personMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameTextType }
     *     
     */
    public PersonNameTextType getPersonMiddleName() {
        return personMiddleName;
    }

    /**
     * Sets the value of the personMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameTextType }
     *     
     */
    public void setPersonMiddleName(PersonNameTextType value) {
        this.personMiddleName = value;
    }

    /**
     * Gets the value of the personSurName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameTextType }
     *     
     */
    public PersonNameTextType getPersonSurName() {
        return personSurName;
    }

    /**
     * Sets the value of the personSurName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameTextType }
     *     
     */
    public void setPersonSurName(PersonNameTextType value) {
        this.personSurName = value;
    }

    /**
     * Gets the value of the personMaidenName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameTextType }
     *     
     */
    public PersonNameTextType getPersonMaidenName() {
        return personMaidenName;
    }

    /**
     * Sets the value of the personMaidenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameTextType }
     *     
     */
    public void setPersonMaidenName(PersonNameTextType value) {
        this.personMaidenName = value;
    }

}
