//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.codes.fbi_ncic._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HAICodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HAICodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="BLD"/>
 *     &lt;enumeration value="BLK"/>
 *     &lt;enumeration value="BLN"/>
 *     &lt;enumeration value="BLU"/>
 *     &lt;enumeration value="BRO"/>
 *     &lt;enumeration value="GRN"/>
 *     &lt;enumeration value="GRY"/>
 *     &lt;enumeration value="ONG"/>
 *     &lt;enumeration value="PLE"/>
 *     &lt;enumeration value="PNK"/>
 *     &lt;enumeration value="RED"/>
 *     &lt;enumeration value="SDY"/>
 *     &lt;enumeration value="WHI"/>
 *     &lt;enumeration value="XXX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HAICodeSimpleType")
@XmlEnum
public enum HAICodeSimpleType {


    /**
     * Bald
     * 
     */
    BLD,

    /**
     * Black
     * 
     */
    BLK,

    /**
     * Blond or Strawberry
     * 
     */
    BLN,

    /**
     * Blue
     * 
     */
    BLU,

    /**
     * Brown
     * 
     */
    BRO,

    /**
     * Green
     * 
     */
    GRN,

    /**
     * Gray or Partially Gray
     * 
     */
    GRY,

    /**
     * Orange
     * 
     */
    ONG,

    /**
     * Purple
     * 
     */
    PLE,

    /**
     * Pink
     * 
     */
    PNK,

    /**
     * Red or Auburn
     * 
     */
    RED,

    /**
     * Sandy
     * 
     */
    SDY,

    /**
     * White
     * 
     */
    WHI,

    /**
     * Unknown or Completely Bald
     * 
     */
    XXX;

    public String value() {
        return name();
    }

    public static HAICodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
