//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 01:23:32 AM EDT 
//


package gov.niem.release.niem.codes.fbi_ncic._3;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niem.release.niem.codes.fbi_ncic._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niem.release.niem.codes.fbi_ncic._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EYECodeType }
     * 
     */
    public EYECodeType createEYECodeType() {
        return new EYECodeType();
    }

    /**
     * Create an instance of {@link HAICodeType }
     * 
     */
    public HAICodeType createHAICodeType() {
        return new HAICodeType();
    }

    /**
     * Create an instance of {@link SEXCodeType }
     * 
     */
    public SEXCodeType createSEXCodeType() {
        return new SEXCodeType();
    }

}
